### ISSUE TITLE
Undefined symbols for architecture arm64: ... 

### ISSUE THREAD

**Issue by yosun** [ThisNetWorks/iVidCapPro#10]
Undefined symbols for architecture arm64:
  "_MTLCreateSystemDefaultDevice", referenced from:
      -[UnityARSession setupMetal] in ARSessionNative.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

(latest ARKit plugin)

**Comment by ThisNetWorks** [comment]
the plugin does not support metal - you'll need to change your unity settings to use OpenGl 2

**Comment by Akevlam** [comment]
Hi Yosun,

Is it the case that ARKit requires the use of Metal?  I've gotten that impression from a bit of reading that I've done.  I'm guessing that maybe you had the Unity settings on openGLES and that's the error Xcode gave you?

If it's true that ARKit requires Metal, it adds additional pressure for iVidCapPro to support Metal in order to remain relevant.
