### ISSUE TITLE
Resolution not supported when recording video on iPhone X

### ISSUE THREAD

**Issue by Kafar** [ThisNetWorks/iVidCapPro#13]
Hello,

On iPhone X the plugin return the exception in subject.
There is some tips?

Thanks

**Comment by TheAppsPajamas** [comment]
Can you send the xcode log file with exception please?

**Comment by Kafar** [comment]
This is not possible because I dont have  the iPhone X and with the emulator I cant  run the code because I use Vuforia with other plugins not compatible with emulator

**Comment by TheAppsPajamas** [comment]
Ok, I have access to one, so I'll try and get it over the weekend and see what I can see

**Comment by thisisdanzo** [comment]
Related to iPhone X having a 19.5:9 aspect ratio; iVidCapPro seems to support 1920x1080 as max resolution?

**Comment by Akevlam** [comment]
As thisisdanzo mentioned, iVidCapPro is limited to 1920x1080 out-of-the-box.  This is a hold-over from when the plugin was originally written and 1920x1080 was larger than any device supported.  You can see the check for this in iVidCapPro.cs on or about line 995.  I'm sorry to say that check is a hack. I can't imagine who would have written such a thing.  ;^P

The simple fix is to just adjust that line to check some larger number that seems reasonable. I believe the remainder of the code will accept any frame size.  A better fix would be to investigate how to make that frame size limit dependent on the device. Note that, in general, it's not simply the device screen size since you may want to record at a resolution larger than the screen size.  For example, an iPhone X may be able to handle recording in 4K.

Developing a more general check would be a great, self-contained contribution to the project!

**Comment by ThisNetWorks** [comment]
I can confirm that changing the resolution check to 2436 on or around line 995 in iVidCapPro.cs
	
```
if (frameWidth < 128 || frameHeight < 128 || frameWidth > 2436 || frameHeight > 2436) {
	Debug.LogWarning("iVidCapPro-BeginRecordingSession called with an unsupported frame size: " 
		+ frameWidth + "x" + frameHeight);
	sessionStatus = SessionStatusCode.Failed_ResolutionNotSupported;
	return sessionStatus;	
}

will support recording on the iPhone X
