### ISSUE TITLE
Video from Images?

### ISSUE THREAD

**Issue by eblabs** [ThisNetWorks/iVidCapPro#15]
Hi,
I couldnt find it in the docs, but is there anything in the API for generating a video from images? or by screen recording and manually triggering the captures frame by frame?

Thanks!

**Comment by ThisNetWorks** [comment]
Not specifically, I've built montages previously by playing images back in unity, and screen capturing, however that was intended to be a slow montage video, rather than an image per frame (which sounds like what you're looking for?)

What's your source of the images? From game, or external? 
It's not hard in objective c to build a video from images

**Comment by eblabs** [comment]
Thanks for the quick response. 

I'm attempting to record a 3D playback of recorded gameplay. Although, at a higher quality setting. It isnt possible to play this back at realtime to record, so Im essentially stepping through frame by frame and recording once the frame is drawn. Its essentially rendering something frame by frame for the purpose of creating a video file that will play back smoothly. Hope this makes sense!

**Comment by Akevlam** [comment]
It sounds like what you want to do is render a video at a fixed frame rate, regardless of how much elapsed time is required.  This is one of the original use cases that motivated iVidCapPro.  If this is what you want to do, you can set the CaptureFramerateLock value to Locked when you invoke BeginRecordingSession.  This will result in Unity's Time.captureFramerate being set to the framerate you specified and recording will proceed at this fixed framerate until you call EndRecordingSession.
